---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: upgrade:"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: upgrade:"
    ignore:
      - dependency-name: "next"
        versions: [">=15.2.0"]
      - dependency-name: "eslint-config-next"
        versions: [">=15.2.0"]
      - dependency-name: "tailwindcss"
        versions: [">=3.4.1"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: upgrade:"
