---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next"
        versions: [">=15.2.0"]
      - dependency-name: "eslint-config-next"
        versions: [">=15.2.0"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
